# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://rludlow.github.io/ndbev_demo/"

git_url = "https://github.com/rludlow/ndbev_demo/tree/master/"

def custom_doc_links(name): return None
